'use client'

import { useMemo, useState } from 'react'
import { motion, AnimatePresence } from 'motion/react'
import { ArrowRight, Bookmark, CalendarDays, ChevronRight, CircleUserRound, Compass, Heart, House, Instagram, Link2, MapPin, Menu, MessageCircle, MoreHorizontal, Search, Share2, Sparkles, Star, Store, Tag, ThumbsUp, Utensils, X } from 'lucide-react'

const categories = ['Todo', 'Comida', 'Café', 'Bares', 'Compras', 'Naturaleza', 'Cultura']
const places = [
  { name: 'Centro Histórico', type: 'Cultura · caminar', cat: 'Cultura', image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1000&q=85', rating: '4.9', reviews: 128, color: 'bg-granizo' },
  { name: 'Cerro de Chignautla', type: 'Naturaleza · aventura', cat: 'Naturaleza', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85', rating: '4.8', reviews: 94, color: 'bg-cerro' },
  { name: 'Café Colonial', type: 'Café · desayuno', cat: 'Café', image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=85', rating: '4.7', reviews: 67, color: 'bg-alerta' },
  { name: 'Santuario del Carmen', type: 'Historia · fotos', cat: 'Cultura', image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1000&q=85', rating: '4.9', reviews: 82, color: 'bg-granizo' },
]
const businesses = [
  { name: 'La Casona de Don Porfirio', kind: 'Restaurante', image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80', rating: '4.8', address: 'Av. Hidalgo 18, Centro' },
  { name: 'Panadería La Sierra', kind: 'Panadería · café', image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80', rating: '4.9', address: 'Calle Allende 42, Centro' },
]

type Tab = 'Inicio' | 'Explorar' | 'Promos' | 'Opiniones' | 'Cuenta'

export default function Page() {
  const [tab, setTab] = useState<Tab>('Inicio')
  const [category, setCategory] = useState('Todo')
  const [query, setQuery] = useState('')
  const [saved, setSaved] = useState<string[]>([])
  const [liked, setLiked] = useState<string[]>([])
  const [menu, setMenu] = useState(false)
  const [comment, setComment] = useState('')
  const [comments, setComments] = useState(['El centro se ve increíble con neblina. ¿Qué café recomiendan?', 'La ruta del cerro temprano está buenísima, lleven chamarra.'])
  const filtered = useMemo(() => places.filter(p => (category === 'Todo' || p.cat === category) && `${p.name} ${p.type}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  const toggle = (items: string[], setItems: (v: string[]) => void, value: string) => setItems(items.includes(value) ? items.filter(x => x !== value) : [...items, value])
  const navigate = (next: Tab) => { setTab(next); setMenu(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }

  return <main className="min-h-screen bg-niebla pb-24 text-grano">
    <header className="sticky top-0 z-40 border-b border-grano/10 bg-niebla/90 px-4 py-3 backdrop-blur-xl sm:px-6"><div className="mx-auto flex max-w-5xl items-center justify-between"><button onClick={() => navigate('Inicio')} className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-xl bg-cerro font-serif text-lg text-perla">H</span><span className="text-left leading-none"><strong className="block font-serif text-lg text-cerro">HOYTEZIU</strong><small className="font-mono text-[8px] uppercase tracking-[.16em] text-granizo">La Perla de la Sierra</small></span></button><div className="flex items-center gap-2"><button onClick={() => navigate('Opiniones')} className="hidden items-center gap-1 rounded-full border border-grano/15 bg-perla px-3 py-2 font-mono text-[9px] font-bold lg:flex"><MessageCircle className="size-3" /> Opina</button><button onClick={() => setMenu(!menu)} aria-label="Abrir menú" className="grid size-9 place-items-center rounded-full bg-cerro text-perla"><Menu className="size-4" /></button></div></div><AnimatePresence>{menu && <motion.nav initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="mx-auto flex max-w-5xl flex-col gap-3 overflow-hidden pt-4 font-sans text-sm font-bold">{(['Explorar', 'Promos', 'Opiniones', 'Cuenta'] as Tab[]).map(item => <button key={item} onClick={() => navigate(item)} className="border-t border-grano/10 pt-3 text-left">{item}</button>)}</motion.nav>}</AnimatePresence></header>

    {tab === 'Inicio' && <>
      <section className="mx-auto max-w-5xl px-4 pb-5 pt-5 sm:px-6"><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="relative h-[390px] overflow-hidden rounded-[28px] bg-cerro shadow-xl sm:h-[450px]"><motion.img initial={{ scale: 1.1 }} animate={{ scale: 1 }} transition={{ duration: 1.4 }} src="/teziutlan-hero.png" alt="Sierra de Teziutlán entre neblina" className="absolute inset-0 size-full object-cover opacity-80" /><div className="absolute inset-0 bg-gradient-to-t from-cerro via-cerro/35 to-transparent" /><div className="absolute left-5 top-5 rounded-full border border-perla/30 bg-cerro/35 px-3 py-2 font-mono text-[9px] uppercase tracking-widest text-perla backdrop-blur-md">Teziutlán, Puebla</div><div className="absolute bottom-5 left-5 right-5"><p className="font-mono text-[10px] uppercase tracking-[.22em] text-perla/65">La guía local</p><h1 className="mt-2 font-serif text-5xl leading-[.9] text-perla sm:text-7xl">Vive la<br /><em className="text-granizo">sierra.</em></h1><div className="mt-5 flex max-w-md items-center gap-2 rounded-2xl bg-perla/95 px-3 py-3 shadow-lg"><Search className="size-4 shrink-0 text-granizo" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Busca un lugar, antojo o plan" aria-label="Buscar lugares" className="min-w-0 flex-1 bg-transparent font-sans text-xs outline-none placeholder:text-grano/45" />{query && <button onClick={() => setQuery('')}><X className="size-4" /></button>}</div></div></motion.div></section>
      <CategoryRow category={category} setCategory={setCategory} />
      <section className="mx-auto max-w-5xl px-4 py-7 sm:px-6"><SectionTitle eyebrow="Descubre cerca" title="Planes para hoy" action="Explorar todo" onAction={() => navigate('Explorar')} /><div className="no-scrollbar -mx-4 flex gap-3 overflow-x-auto px-4 pb-2 sm:mx-0 sm:px-0">{filtered.slice(0, 4).map((place, i) => <PlaceCard key={place.name} place={place} index={i} saved={saved} setSaved={setSaved} liked={liked} setLiked={setLiked} />)}</div></section>
      <section className="mx-auto max-w-5xl px-4 pb-8 sm:px-6"><div className="rounded-3xl bg-cerro p-5 text-perla"><div className="flex items-start justify-between"><div><p className="font-mono text-[9px] uppercase tracking-widest text-perla/55">Comunidad local</p><h2 className="mt-1 font-serif text-3xl">¿Qué plan traes?</h2></div><Sparkles className="size-5 text-granizo" /></div><p className="mt-2 max-w-sm font-sans text-xs leading-5 text-perla/65">Comparte tu descubrimiento y ayuda a que más gente conozca Teziutlán.</p><button onClick={() => navigate('Opiniones')} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-perla py-3 font-sans text-xs font-bold text-cerro">Entrar a la conversación <ArrowRight className="size-4" /></button></div></section>
    </>}

    {tab === 'Explorar' && <Explore query={query} setQuery={setQuery} category={category} setCategory={setCategory} saved={saved} setSaved={setSaved} liked={liked} setLiked={setLiked} navigate={navigate} />}
    {tab === 'Promos' && <Promos navigate={navigate} />}
    {tab === 'Opiniones' && <Opinions comment={comment} setComment={setComment} comments={comments} setComments={setComments} />}
    {tab === 'Cuenta' && <Account navigate={navigate} />}

    <footer className="mx-auto flex max-w-5xl items-center justify-between border-t border-grano/10 px-4 py-7 sm:px-6"><span className="font-serif text-lg text-cerro">HOYTEZIU</span><button onClick={() => navigate('Cuenta')} className="font-mono text-[9px] text-granizo">Tu negocio en HOYTEZIU →</button></footer>
    <nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-grano/10 bg-perla/95 px-4 py-2.5 backdrop-blur-xl"><div className="mx-auto flex max-w-md items-center justify-between">{([['Inicio', House], ['Explorar', Compass], ['Promos', Tag], ['Opiniones', MessageCircle], ['Cuenta', CircleUserRound]] as const).map(([label, Icon]) => <button key={label} onClick={() => navigate(label)} className={`flex min-w-12 flex-col items-center gap-1 font-mono text-[8px] ${tab === label ? 'text-granizo' : 'text-grano/45'}`}><Icon className="size-[18px]" /><span>{label}</span></button>)}</div></nav>
  </main>
}

function CategoryRow({ category, setCategory }: { category: string, setCategory: (x: string) => void }) { return <div className="no-scrollbar mx-auto flex max-w-5xl gap-2 overflow-x-auto px-4 sm:px-6">{categories.map(cat => <button key={cat} onClick={() => setCategory(cat)} className={`shrink-0 rounded-full px-4 py-2 font-mono text-[10px] font-bold transition ${category === cat ? 'bg-cerro text-perla' : 'border border-grano/15 bg-perla text-grano/60'}`}>{cat}</button>)}</div> }
function SectionTitle({ eyebrow, title, action, onAction }: { eyebrow: string, title: string, action: string, onAction: () => void }) { return <div className="mb-4 flex items-end justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.2em] text-granizo">{eyebrow}</p><h2 className="mt-1 font-serif text-3xl leading-none text-cerro">{title}</h2></div><button onClick={onAction} className="flex items-center gap-1 font-sans text-xs font-bold text-granizo">{action} <ChevronRight className="size-3" /></button></div> }
function PlaceCard({ place, index, saved, setSaved, liked, setLiked }: any) { return <motion.article initial={{ opacity: 0, x: 18 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * .07 }} className="min-w-[235px] overflow-hidden rounded-2xl border border-grano/10 bg-perla shadow-sm sm:min-w-0 sm:flex-1"><div className="relative aspect-[1.18] overflow-hidden"><img src={place.image} alt={place.name} loading="lazy" className="size-full object-cover transition duration-700 hover:scale-110" /><span className={`absolute left-2.5 top-2.5 rounded-full ${place.color} px-2 py-1 font-mono text-[8px] font-bold uppercase tracking-wide text-perla`}>{place.cat}</span><button onClick={() => setSaved(saved.includes(place.name) ? saved.filter((x: string) => x !== place.name) : [...saved, place.name])} aria-label="Guardar" className="absolute right-2.5 top-2.5 grid size-8 place-items-center rounded-full bg-cerro/60 text-perla backdrop-blur-sm"><Bookmark className={`size-4 ${saved.includes(place.name) ? 'fill-perla' : ''}`} /></button></div><div className="p-3"><h3 className="font-serif text-lg leading-tight text-cerro">{place.name}</h3><p className="mt-1 font-sans text-[10px] text-grano/55">{place.type}</p><div className="mt-3 flex items-center justify-between"><span className="flex items-center gap-1 font-mono text-[9px] text-grano/55"><Star className="size-3 fill-alerta text-alerta" /> {place.rating} · {place.reviews}</span><button onClick={() => setLiked(liked.includes(place.name) ? liked.filter((x: string) => x !== place.name) : [...liked, place.name])} className="font-mono text-[9px] font-bold text-granizo"><Heart className={`mr-1 inline size-3 ${liked.includes(place.name) ? 'fill-alerta text-alerta' : ''}`} />Me gusta</button></div></div></motion.article> }
function Explore({ query, setQuery, category, setCategory, saved, setSaved, liked, setLiked, navigate }: any) { return <section className="mx-auto max-w-5xl px-4 py-7 sm:px-6"><p className="font-mono text-[9px] uppercase tracking-[.2em] text-granizo">Explora Teziutlán</p><h1 className="mt-2 font-serif text-5xl leading-none text-cerro">Todo lo que<br /><em className="text-granizo">te mueve.</em></h1><div className="mt-6 flex items-center gap-2 rounded-2xl border border-grano/10 bg-perla px-3 py-3"><Search className="size-4 text-granizo" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Restaurantes, senderos, cafés..." className="flex-1 bg-transparent font-sans text-xs outline-none" /></div><div className="mt-5"><CategoryRow category={category} setCategory={setCategory} /></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{places.map((p, i) => <PlaceCard key={p.name} place={p} index={i} saved={saved} setSaved={setSaved} liked={liked} setLiked={setLiked} />)}</div><button onClick={() => navigate('Cuenta')} className="mt-7 flex w-full items-center justify-center gap-2 rounded-2xl border border-dashed border-granizo/40 bg-granizo/5 p-5 font-sans text-xs font-bold text-granizo"><Store className="size-4" /> ¿Tienes un negocio? Regístralo gratis</button></section> }
function Promos({ navigate }: any) { return <section className="mx-auto max-w-5xl px-4 py-7 sm:px-6"><p className="font-mono text-[9px] uppercase tracking-[.2em] text-alerta">Solo por hoy</p><h1 className="mt-2 font-serif text-5xl leading-none text-cerro">Promos que<br /><em className="text-alerta">sí antojan.</em></h1><div className="mt-7 grid gap-4 sm:grid-cols-2">{businesses.map((b, i) => <motion.article whileTap={{ scale: .98 }} key={b.name} className="overflow-hidden rounded-3xl bg-perla shadow-sm"><div className="relative h-48"><img src={b.image} alt={b.name} className="size-full object-cover" /><span className="absolute left-3 top-3 rounded-full bg-alerta px-3 py-1 font-mono text-[9px] font-bold text-perla">{i ? '2x1 café' : '15% OFF'}</span></div><div className="p-4"><div className="flex justify-between"><div><h2 className="font-serif text-2xl text-cerro">{b.name}</h2><p className="font-sans text-xs text-grano/55">{b.kind} · {b.address}</p></div><Star className="size-4 fill-alerta text-alerta" /></div><button onClick={() => navigate('Explorar')} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-cerro py-3 font-sans text-xs font-bold text-perla">Ver negocio <ArrowRight className="size-3" /></button></div></motion.article>)}</div></section> }
function Opinions({ comment, setComment, comments, setComments }: any) { return <section className="mx-auto max-w-2xl px-4 py-7 sm:px-6"><p className="font-mono text-[9px] uppercase tracking-[.2em] text-granizo">La conversación local</p><h1 className="mt-2 font-serif text-5xl leading-none text-cerro">¿Qué opinas<br /><em className="text-granizo">de Teziu?</em></h1><div className="mt-7 rounded-3xl bg-cerro p-5 text-perla"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-granizo"><CircleUserRound className="size-5" /></div><div><p className="font-sans text-xs font-bold">Comunidad HOYTEZIU</p><p className="font-mono text-[9px] text-perla/50">Comparte algo con la banda</p></div></div><textarea value={comment} onChange={e => setComment(e.target.value)} placeholder="Un lugar que descubriste, una recomendación..." className="mt-5 min-h-28 w-full resize-none rounded-2xl border border-perla/15 bg-perla/10 p-3 font-sans text-xs outline-none placeholder:text-perla/40" /><button onClick={() => { if (comment.trim()) { setComments([comment, ...comments]); setComment('') } }} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-perla py-3 font-sans text-xs font-bold text-cerro">Publicar comentario <ArrowRight className="size-3" /></button></div><div className="mt-7 flex flex-col gap-3">{comments.map((c: string, i: number) => <article key={`${c}-${i}`} className="rounded-2xl border border-grano/10 bg-perla p-4"><div className="flex items-center justify-between"><span className="font-mono text-[9px] text-granizo">@viajero_serrano</span><MoreHorizontal className="size-4 text-grano/40" /></div><p className="mt-3 font-sans text-sm leading-6">{c}</p><div className="mt-3 flex gap-4 font-mono text-[9px] text-grano/45"><span><ThumbsUp className="mr-1 inline size-3" /> Me gusta</span><span>Responder</span></div></article>)}</div></section> }
function Account({ navigate }: { navigate: (x: Tab) => void }) { return <section className="mx-auto max-w-2xl px-4 py-7 sm:px-6"><div className="rounded-3xl bg-cerro p-6 text-perla"><div className="grid size-14 place-items-center rounded-2xl bg-granizo"><CircleUserRound className="size-7" /></div><h1 className="mt-5 font-serif text-4xl">Tu espacio en<br /><em className="text-granizo">HOYTEZIU.</em></h1><p className="mt-3 font-sans text-xs leading-5 text-perla/65">Guarda tus lugares favoritos, comparte reseñas y administra tu negocio desde un solo lugar.</p><div className="mt-6 grid gap-2"><button onClick={() => navigate('Inicio')} className="rounded-xl bg-perla py-3 font-sans text-xs font-bold text-cerro">Crear mi cuenta</button><button className="rounded-xl border border-perla/25 py-3 font-sans text-xs font-bold">Ya tengo cuenta · Iniciar sesión</button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button className="flex items-center gap-3 rounded-2xl border border-grano/10 bg-perla p-4 text-left"><Store className="size-5 text-granizo" /><span><strong className="block font-sans text-xs">Registrar negocio</strong><small className="font-mono text-[9px] text-grano/50">Crea tu perfil público</small></span></button><button className="flex items-center gap-3 rounded-2xl border border-grano/10 bg-perla p-4 text-left"><Link2 className="size-5 text-granizo" /><span><strong className="block font-sans text-xs">Mi link público</strong><small className="font-mono text-[9px] text-grano/50">Comparte tu negocio</small></span></button></div><div className="mt-6 rounded-2xl border border-granizo/20 bg-granizo/5 p-4"><p className="font-mono text-[9px] uppercase tracking-widest text-granizo">Panel para negocios</p><p className="mt-2 font-sans text-xs leading-5 text-grano/70">Edita fotos, horarios, redes sociales, menú, promociones y responde reseñas desde tu panel.</p><button className="mt-3 flex items-center gap-2 font-sans text-xs font-bold text-granizo">Conocer más <ArrowRight className="size-3" /></button></div></section> }
